metadata:
  name: "tcpcollect"
apiVersion: "mz.digitalroute.com/v1alpha1"
kind: "ECDeployment"
spec:
  ecGroups: "tcpcollect"
  jvmArgs:
  - "Xms512m"
  - "Xmx512m"
  exportJmxMetrics: false
  resources:
    requests:
      memory: "320.0Mi"
      cpu: "500m"
    limits:
      memory: "640.0Mi"
      cpu: "1000m"
  workflows:
  - template: "tcp.collect"
    instances:
    - name: "collect3211"
      useExtRef: "{}"
      parameters: "{\"TcpPort\":3211}"
    packageVersion: "1.0"
    packageName: "TcpCollect"
  services:
  - spec:
      type: "LoadBalancer"
      ports:
      - protocol: "TCP"
        port: 3211
        name: "port-0"
        targetPort: 3211
  manualUpgrade: false
  ports:
  - containerPort: 3211
  autoscale:
    maxReplicas: 4
    minReplicas: 1
    metrics:
    - resource:
        name: "cpu"
        target:
          averageUtilization: 50
          type: "Utilization"
      type: "Resource"

