metadata:
  name: "petstore"
apiVersion: "mz.digitalroute.com/v1alpha1"
kind: "ECDeployment"
spec:
  ecGroups: "petstore"
  jvmArgs:
  - "Xms256m"
  - "Xmx256m"
  ingress:
    paths:
    - path: "/pets"
      port: 8899
    host: "ingress.example.digitalroute.net"
    tlsSecretName: "mz-cert"
  exportJmxMetrics: false
  resources:
    requests:
      memory: "320.0Mi"
      cpu: "500m"
    limits:
      memory: "320.0Mi"
      cpu: "1000m"
  disabled: false
  workflows:
  - template: "http.HttpServer"
    instances:
    - name: "server"
      useExtRef: "{}"
      parameters: "{}"
    packageVersion: null
    packageName: null
  manualUpgrade: false
  ports:
  - containerPort: 8899
  autoscale:
    maxReplicas: 4
    minReplicas: 1
    metrics:
    - resource:
        name: "cpu"
        target:
          averageUtilization: 50
          type: "Utilization"
      type: "Resource"
